In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv(r"C:\Users\anikk\Downloads\marketing_campaign_data_cleaned.csv")
print(df.to_string())

     Campaign_ID             Campaign_Name  Start_Date    End_Date     Channel  Impressions  Clicks      Spend  Conversions Active   CTR      CPC  Conversion_Rate  Cost_Per_Conversion
0      CMP-00001       Q4_Summer_CMP-00001  2023-11-24  2023-12-13      TikTok        16795     197        NaN         20.0    Yes  1.17      NaN            10.15                  NaN
1      CMP-00002       Q1_Launch_CMP-00002  2023-05-06  2023-05-12    Facebook         1860      30      24.33          1.0     No  1.61     0.81             3.33                24.33
2      CMP-00003       Q3_Winter_CMP-00003  2023-12-13  2023-12-20       Email        77820     843    1323.39         51.0     No  1.08     1.57             6.05                25.95
3      CMP-00004  Q1_BlackFriday_CMP-00004  2023-10-30  2023-11-03      TikTok        55886    2019    2180.38        135.0    Yes  3.61     1.08             6.69                16.15
4      CMP-00005       Q2_Winter_CMP-00005  2023-04-22  2023-04-23    Facebook         7265     169     252.44         30.0    Yes  2.33     1.49            17.75                 8.41
5      CMP-00006  Q4_BlackFriday_CMP-00006  2023-10-15  2023-10-28   Instagram        83386    2643    2697.03          NaN    Yes  3.17     1.02              NaN                  NaN
6      CMP-00007       Q3_Launch_CMP-00007  2023-10-07  2023-10-23    Facebook        38194    1135    1232.76        178.0    Yes  2.97     1.09            15.68                 6.93
7      CMP-00008       Q4_Launch_CMP-00008  2023-05-23  2023-05-28   Instagram        88498    1173     865.70        127.0    Yes  1.33     0.74            10.83                 6.82
8      CMP-00009  Q4_BlackFriday_CMP-00009  2023-03-23  2023-04-01  Google Ads        45131    1179    1046.18        104.0    Yes  2.61     0.89             8.82                10.06
9      CMP-00010       Q2_Winter_CMP-00010  2023-03-21  2023-04-01       Email        61263    1153    1623.56          NaN     No  1.88     1.41              NaN                  NaN
10     CMP-00011       Q4_Launch_CMP-00011  2023-02-22  2023-03-01   Instagram        17023     455     523.13         76.0    Yes  2.67     1.15            16.70                 6.88
11     CMP-00012       Q4_Launch_CMP-00012  2023-02-19  2023-02-20  Google Ads        42090     763    1267.69        109.0     No  1.81     1.66            14.29                11.63
12     CMP-00013       Q2_Launch_CMP-00013  2023-05-16  2023-06-01  Google Ads        68221    2975    5292.16        567.0     No  4.36     1.78            19.06                 9.33
13     CMP-00014       Q1_Launch_CMP-00014  2023-10-02  2023-10-15      TikTok        65820    1116    1464.72        169.0    Yes  1.70     1.31            15.14                 8.67
14     CMP-00015       Q2_Summer_CMP-00015  2023-02-10  2023-02-16  Google Ads         1769      85     139.18         11.0    Yes  4.80     1.64            12.94                12.65
15     CMP-00016  Q2_BlackFriday_CMP-00016  2023-11-13  2023-11-23       Email        60735    1617    1552.90        228.0    Yes  2.66     0.96            14.10                 6.81
16     CMP-00017       Q1_Winter_CMP-00017  2023-04-09  2023-10-01       Email        63955    2804    3147.37        536.0     No  4.38     1.12            19.12                 5.87
17     CMP-00018  Q1_BlackFriday_CMP-00018  2023-04-27  2023-05-25   Instagram        65925    2317    3635.76        389.0    Yes  3.51     1.57            16.79                 9.35
18     CMP-00019       Q4_Winter_CMP-00019  2023-04-30  2023-05-18    Facebook        68969    2718    2933.59        145.0     No  3.94     1.08             5.33                20.23
19     CMP-00020       Q1_Summer_CMP-00020  2023-08-21  2023-08-30       Email         6311     256     353.99          NaN    Yes  4.06     1.38              NaN                  NaN
20     CMP-00021  Q3_BlackFriday_CMP-00021  2023-07-09  2023-07-17    Facebook        84104    2539    1975.49          NaN    Yes  3.02     0.78              NaN                  NaN
21     CMP-00022  Q2_BlackFriday_CMP-00022  2023-12-26  2024-01-02  Google Ads        54707    1735        NaN          NaN    Yes  3.17      NaN              NaN                  NaN
22     CMP-00023       Q4_Winter_CMP-00023  2023-11-08  2023-11-24  Google Ads        86305    2637        NaN        216.0     No  3.06      NaN             8.19                  NaN
23     CMP-00024       Q4_Winter_CMP-00024  2023-05-06  2023-05-01   Instagram        29693     995    1793.94        179.0     No  3.35     1.80            17.99                10.02
24     CMP-00025       Q2_Winter_CMP-00025  2023-11-24  2023-12-18       Email        72932     815    1293.01        157.0     No  1.12     1.59            19.26                 8.24
25     CMP-00026       Q1_Winter_CMP-00026  2023-06-16  2023-07-02  Google Ads        94016    2427    3928.42        207.0     No  2.58     1.62             8.53                18.98
26     CMP-00027       Q1_Winter_CMP-00027  2023-04-28  2023-05-12      TikTok        26658     912    1219.24        166.0    Yes  3.42     1.34            18.20                 7.34
27     CMP-00028       Q4_Summer_CMP-00028  2023-07-25  2023-08-08       Email        85478    2898    3990.55        187.0    Yes  3.39     1.38             6.45                21.34
28     CMP-00029  Q4_BlackFriday_CMP-00029  2023-10-18  2023-11-15   Instagram        19431     810     567.39         47.0    Yes  4.17     0.70             5.80                12.07
29     CMP-00030       Q1_Summer_CMP-00030  2023-12-02  2023-12-08   Instagram         3747     135     157.38          9.0     No  3.60     1.17             6.67                17.49
30     CMP-00031       Q1_Launch_CMP-00031  2023-11-26  2023-12-12  Google Ads        60150    2988    3514.38        175.0    Yes  4.97     1.18             5.86                20.08
31     CMP-00032       Q2_Summer_CMP-00032  2023-05-07  2023-05-29   Instagram        66725    1424        NaN        251.0    Yes  2.13      NaN            17.63                  NaN
32     CMP-00033  Q2_BlackFriday_CMP-00033  2023-10-27  2023-10-29   Instagram        85654    2087        NaN        122.0     No  2.44      NaN             5.85                  NaN
33     CMP-00034       Q2_Summer_CMP-00034  2023-07-05  2023-07-17    Facebook        36773     932    1233.98         84.0     No  2.53     1.32             9.01                14.69
34     CMP-00035       Q2_Summer_CMP-00035  2023-09-18  2023-09-22   Instagram        68435    1959    2546.46        128.0    Yes  2.86     1.30             6.53                19.89
35     CMP-00036       Q1_Launch_CMP-00036  2023-02-26  2023-03-01      TikTok        57886    2514    3658.23        237.0    Yes  4.34     1.46             9.43                15.44
36     CMP-00037       Q2_Winter_CMP-00037  2023-12-15  2023-12-26   Instagram        67803    1317        NaN         83.0    Yes  1.94      NaN             6.30                  NaN
37     CMP-00038       Q4_Winter_CMP-00038  2023-07-15  2023-08-07      TikTok        32551    1335        NaN        200.0    Yes  4.10      NaN            14.98                  NaN
38     CMP-00039       Q3_Launch_CMP-00039  2023-05-09  2023-05-25       Email        12394     324     418.96         22.0    Yes  2.61     1.29             6.79                19.04
39     CMP-00040  Q4_BlackFriday_CMP-00040  2023-01-06  2023-01-26       Email        70092    2388    4152.44        424.0     No  3.41     1.74            17.76                 9.79
40     CMP-00041       Q4_Summer_CMP-00041  2023-10-02  2023-10-12       Email         4890     172        NaN         29.0    Yes  3.52      NaN            16.86                  NaN
41     CMP-00042       Q3_Summer_CMP-00042  2023-06-24  2023-06-29      TikTok        42606    1061     973.67         55.0    Yes  2.49     0.92             5.18                17.70
42     CMP-00043       Q2_Summer_CMP-00043  2023-08-21  2023-08-29   Instagram        97276    2967    4397.28        546.0    Yes  3.05     1.48            18.40                 8.05
43     CMP-00044       Q1_Winter_CMP-00044  2023-05-15  2023-06-01       Email        81038    2149    3729.91        116.0    Yes  2.65     1.74             5.40                32.15
44     CMP-00045       Q2_Summer_CMP-00045  2023-09-17  2023-10-03      TikTok        88313    1127     670.24         96.0     No  1.28     0.59             8.52                 6.98
45     CMP-00046       Q4_Launch_CMP-00046  2023-06-02  2023-06-28   Instagram        11627     319     531.19         17.0    Yes  2.74     1.67             5.33                31.25
46     CMP-00047  Q4_BlackFriday_CMP-00047  2023-04-12  2023-04-19  Google Ads         9792     136     235.62         13.0    Yes  1.39     1.73             9.56                18.12
47     CMP-00048       Q3_Winter_CMP-00048  2023-10-04  2023-10-18       Email        74969    1964    2341.65        249.0    Yes  2.62     1.19            12.68                 9.40
48     CMP-00049       Q4_Winter_CMP-00049  2023-01-01  2023-01-17    Facebook        44001    1483    2928.86          NaN     No  3.37     1.97              NaN                  NaN
49     CMP-00050       Q3_Summer_CMP-00050  2023-02-27  2023-02-28       Email        77552    2572    4321.12        258.0    Yes  3.32     1.68            10.03                16.75
50     CMP-00051       Q4_Winter_CMP-00051  2023-06-07  2023-06-17  Google Ads        24897     908    1507.73        141.0    Yes  3.65     1.66            15.53                10.69
51     CMP-00052       Q2_Launch_CMP-00052  2023-10-18  2023-11-08      TikTok        69148     954    1547.16         74.0     No  1.38     1.62             7.76                20.91
52     CMP-00053       Q1_Winter_CMP-00053  2023-09-06  2023-09-12    Facebook        24483     883     640.98          NaN     No  3.61     0.73              NaN                  NaN
53     CMP-00054       Q4_Winter_CMP-00054  2023-09-30  2023-10-11         NaN        49555    1114        NaN         95.0     No  2.25      NaN             8.53                  NaN
54     CMP-00055       Q1_Launch_CMP-00055  2023-09-01  2023-08-27  Google Ads        18159     471     563.31         33.0     No  2.59     1.20             7.01                17.07
55     CMP-00056  Q4_BlackFriday_CMP-00056  2023-09-28  2023-10-08    Facebook        81077    3593        NaN        279.0     No  4.43      NaN             7.77                  NaN
56     CMP-00057       Q4_Launch_CMP-00057  2023-04-19  2023-05-11       Email        36920     382     428.93         29.0    Yes  1.03     1.12             7.59                14.79
57     CMP-00058       Q2_Summer_CMP-00058  2023-12-20  2024-01-09      TikTok        93067    3121    5719.84        396.0    Yes  3.35     1.83            12.69                14.44
58     CMP-00059       Q3_Launch_CMP-00059  2023-12-10  2023-12-24    Facebook        68121    2312        NaN        408.0    Yes  3.39      NaN            17.65                  NaN
59     CMP-00060  Q2_BlackFriday_CMP-00060  2023-09-22  2023-10-12       Email        70479    1823    2634.34        112.0    Yes  2.59     1.45             6.14                23.52
60     CMP-00061       Q1_Summer_CMP-00061  2023-02-02  2023-02-06  Google Ads        90475    1762    3149.01        274.0    Yes  1.95     1.79            15.55                11.49
61     CMP-00062  Q1_BlackFriday_CMP-00062  2023-04-28  2023-05-18  Google Ads        20457     396     663.56         58.0    Yes  1.94     1.68            14.65                11.44
62     CMP-00063       Q3_Summer_CMP-00063  2023-12-29  2024-01-03    Facebook        67557    3063    3502.47        554.0     No  4.53     1.14            18.09                 6.32
63     CMP-00064  Q2_BlackFriday_CMP-00064  2023-01-17  2023-02-03       Email        78189    2164    1734.66        187.0    Yes  2.77     0.80             8.64                 9.28
64     CMP-00065       Q2_Summer_CMP-00065  2023-05-02  2023-05-12       Email        79953    1857    2360.81        218.0     No  2.32     1.27            11.74                10.83
65     CMP-00066       Q1_Winter_CMP-00066  2023-10-04  2023-10-15      TikTok        53995    1509    2420.95        285.0    Yes  2.79     1.60            18.89                 8.49
66     CMP-00067  Q1_BlackFriday_CMP-00067  2023-10-20  2023-11-13  Google Ads        41757    1535    1772.36          NaN    Yes  3.68     1.15              NaN                  NaN
67     CMP-00068       Q2_Winter_CMP-00068  2023-08-31  2023-09-12    Facebook        10692     169     253.53         18.0    Yes  1.58     1.50            10.65                14.08
68     CMP-00069       Q1_Winter_CMP-00069  2023-02-19  2023-03-17       Email        46758    1308     839.07         91.0    Yes  2.80     0.64             6.96                 9.22
69     CMP-00070       Q3_Summer_CMP-00070  2023-07-30  2023-08-22       Email        73409    2460    3990.14        219.0    Yes  3.35     1.62             8.90                18.22
70     CMP-00071       Q1_Launch_CMP-00071  2023-12-11  2024-01-08      TikTok        72211    3462    5951.42        474.0    Yes  4.79     1.72            13.69                12.56
71     CMP-00072       Q1_Summer_CMP-00072  2023-02-01  2023-01-27       Email        66697    1340        NaN          NaN    Yes  2.01      NaN              NaN                  NaN
72     CMP-00073       Q3_Summer_CMP-00073  2023-02-25  2023-03-09  Google Ads        38065     927        NaN          NaN     No  2.44      NaN              NaN                  NaN
73     CMP-00074       Q3_Summer_CMP-00074  2023-08-18  2023-09-06       Email        93093    2343    4076.77        327.0     No  2.52     1.74            13.96                12.47
74     CMP-00075  Q3_BlackFriday_CMP-00075  2023-08-25  2023-09-10      TikTok        33606    1150    2132.84        152.0    Yes  3.42     1.85            13.22                14.03
75     CMP-00076       Q4_Winter_CMP-00076  2023-08-15  2023-08-18       Email        12534     304     577.71         38.0    Yes  2.43     1.90            12.50                15.20
76     CMP-00077       Q3_Launch_CMP-00077  2023-02-20  2023-02-21  Google Ads        95663    2998    5102.66        460.0     No  3.13     1.70            15.34                11.09
77     CMP-00078       Q3_Winter_CMP-00078  2023-10-04  2023-10-19       Email        41397    1708    2581.45        299.0     No  4.13     1.51            17.51                 8.63
78     CMP-00079  Q1_BlackFriday_CMP-00079  2023-05-02  2023-05-14  Google Ads        92387    3530    1795.28        347.0    Yes  3.82     0.51             9.83                 5.17
79     CMP-00080       Q4_Summer_CMP-00080  2023-04-20  2023-05-04    Facebook         2016      56        NaN         10.0    Yes  2.78      NaN            17.86                  NaN
80     CMP-00081       Q2_Summer_CMP-00081  2023-03-26  2023-04-03       Email        90789    4046    5489.38        299.0    Yes  4.46     1.36             7.39                18.36
81     CMP-00082       Q4_Launch_CMP-00082  2023-05-16  2023-05-23      TikTok        56591    1829    1748.61        138.0     No  3.23     0.96             7.55                12.67
82     CMP-00083  Q1_BlackFriday_CMP-00083  2023-05-27  2023-06-07   Instagram        90812    2869        NaN        258.0    Yes  3.16      NaN             8.99                  NaN
83     CMP-00084       Q2_Winter_CMP-00084  2023-10-12  2023-11-04   Instagram        24247     275     533.98         18.0     No  1.13     1.94             6.55                29.67
84     CMP-00085       Q4_Summer_CMP-00085  2023-04-08  2023-04-16       Email        25300    1251    2298.80        105.0    Yes  4.94     1.84             8.39                21.89
85     CMP-00086       Q1_Winter_CMP-00086  2023-10-24  2023-11-23  Google Ads        75065    1119    1984.85         73.0    Yes  1.49     1.77             6.52                27.19
86     CMP-00087       Q2_Winter_CMP-00087  2023-06-10  2023-07-08   Instagram        83798    1612    1787.74        279.0    Yes  1.92     1.11            17.31                 6.41
87     CMP-00088  Q2_BlackFriday_CMP-00088  2023-10-27  2023-11-25   Instagram        10268     123      64.03          8.0     No  1.20     0.52             6.50                 8.00
88     CMP-00089       Q4_Winter_CMP-00089  2023-09-29  2023-10-10         NaN        87807    3125    1938.54        506.0    Yes  3.56     0.62            16.19                 3.83
89     CMP-00090  Q3_BlackFriday_CMP-00090  2023-02-11  2023-11-23   Instagram        13185     250     242.07         14.0    Yes  1.90     0.97             5.60                17.29
90     CMP-00091       Q3_Launch_CMP-00091  2023-02-04  2023-03-06   Instagram        64704    1112     582.26        213.0    Yes  1.72     0.52            19.15                 2.73
91     CMP-00092       Q1_Launch_CMP-00092  2023-03-03  2023-04-01  Google Ads        87779    1188        NaN        186.0     No  1.35      NaN            15.66                  NaN
92     CMP-00093       Q2_Winter_CMP-00093  2023-10-24  2023-11-09  Google Ads        40099     566    1061.20         28.0     No  1.41     1.87             4.95                37.90
93     CMP-00094       Q1_Winter_CMP-00094  2023-08-03  2023-08-29         NaN         9571     319     497.40         52.0     No  3.33     1.56            16.30                 9.57
94     CMP-00095       Q4_Summer_CMP-00095  2023-06-11  2023-06-20      TikTok        39044    1465    1411.43        186.0    Yes  3.75     0.96            12.70                 7.59
95     CMP-00096       Q1_Winter_CMP-00096  2023-06-10  2023-06-28  Google Ads        52214    1352     945.00        225.0     No  2.59     0.70            16.64                 4.20
96     CMP-00097       Q3_Summer_CMP-00097  2023-12-10  2023-12-21       Email        62228    1816    2301.70        233.0     No  2.92     1.27            12.83                 9.88
97     CMP-00098       Q4_Summer_CMP-00098  2023-02-07  2023-02-26         NaN        49984    1871     950.50        273.0     No  3.74     0.51            14.59                 3.48
98     CMP-00099  Q4_BlackFriday_CMP-00099  2023-11-15  2023-12-11   Instagram        41774     446     850.80         74.0     No  1.07     1.91            16.59                11.50
99     CMP-00100  Q2_BlackFriday_CMP-00100  2023-02-07  2023-02-18      TikTok         3568      81        NaN          8.0    Yes  2.27      NaN             9.88                  NaN
100    CMP-00101       Q2_Summer_CMP-00101  2023-03-09  2023-04-01      TikTok        63592    3111    3433.00        156.0     No  4.89     1.10             5.01                22.01
101    CMP-00102  Q3_BlackFriday_CMP-00102  2023-05-06  2023-05-13  Google Ads        68563    2276    2471.49        403.0    Yes  3.32     1.09            17.71                 6.13
102    CMP-00103       Q3_Summer_CMP-00103  2023-10-06  2023-11-04         NaN         3695      74        NaN          7.0     No  2.00      NaN             9.46                  NaN
103    CMP-00104       Q1_Winter_CMP-00104  2023-12-01  2023-12-06       Email        49190    1518    2212.46        188.0    Yes  3.09     1.46            12.38                11.77
104    CMP-00105  Q4_BlackFriday_CMP-00105  2023-10-11  2023-10-22      TikTok         6258     148     236.73          7.0    Yes  2.36     1.60             4.73                33.82
105    CMP-00106  Q4_BlackFriday_CMP-00106  2023-03-10  2023-04-05  Google Ads        88538    2770    4194.30        342.0     No  3.13     1.51            12.35                12.26
106    CMP-00107       Q4_Winter_CMP-00107  2023-10-11  2023-11-01  Google Ads        40504     608     430.25        120.0     No  1.50     0.71            19.74                 3.59

In [2]:
print(f"negative spend: {(df['Spend']<0).sum()}")
print(f"negative CPC: {(df['CPC']<0).sum()}")
print(f"negative Cost_Per_Conversion: {(df['Cost_Per_Conversion']<0).sum()}")

negative spend: 19
negative CPC: 19
negative Cost_Per_Conversion: 18

In [3]:
print('negative count: ')
print(df[df['Spend']<0][['Campaign_ID', 'Channel', 'Spend', 'Clicks', 'CPC', 'Cost_Per_Conversion']].count())
print(df[df['Spend']<0][['Campaign_ID', 'Channel', 'Spend', 'Clicks', 'CPC', 'Cost_Per_Conversion']].head(10))

negative count:
Campaign_ID            19
Channel                17
Spend                  19
Clicks                 19
CPC                    19
Cost_Per_Conversion    18
dtype: int64
     Campaign_ID     Channel    Spend  Clicks   CPC  Cost_Per_Conversion
144    CMP-00145    Facebook -1407.54    1859 -0.76                -5.21
407    CMP-00408    Facebook -1214.52    2058 -0.59               -10.21
576    CMP-00577    Facebook  -821.80     940 -0.87                -4.62
604    CMP-00605       Email  -942.80     515 -1.83               -16.54
676    CMP-00677      TikTok -1640.88    1025 -1.60               -25.64
817    CMP-00818       Email -1261.81    1291 -0.98               -15.39
886    CMP-00887  Google Ads -2162.50    2292 -0.94               -14.42
924    CMP-00925    Facebook  -648.30    1054 -0.62                -6.23
1125   CMP-01126      TikTok  -122.80     204 -0.60                -4.91
1142   CMP-01143         NaN   -20.05      29 -0.69               -10.02

In [4]:
df['Spend']=df['Spend'].abs()
df['CPC']=df['CPC'].abs()
df['Cost_Per_Conversion']=df['Cost_Per_Conversion'].abs()

In [5]:
# Verify: আর কোনো negative value নেই
print(f"negative spend: {(df['Spend']<0).sum()}")
print(f"negative CPC: {(df['CPC']<0).sum()}")
print(f"negative Cost_Per_Conversion: {(df['Cost_Per_Conversion']<0).sum()}")
print()
print("Min Spend:", df['Spend'].min())
print("Min CPC:", df['CPC'].min())
print("Min Cost_Per_Conversion:", df['Cost_Per_Conversion'].min())
print("-"*60)
print("Max Spend:", df['Spend'].max())
print("Max CPC:", df['CPC'].max())
print("Max Cost_Per_Conversion:", df['Cost_Per_Conversion'].max())

negative spend: 0
negative CPC: 0
negative Cost_Per_Conversion: 0

Min Spend: 10.01
Min CPC: 0.5
Min Cost_Per_Conversion: 0.0
------------------------------------------------------------
Max Spend: 500000.0
Max CPC: 2590.67
Max Cost_Per_Conversion: 3125.0

In [6]:
Q1=df['Spend'].quantile(0.25)
Q3=df['Spend'].quantile(0.75)
IQR= Q3-Q1
upper_spend = Q3+1.5*IQR
median_spend=df['Spend'].median()

print("Q1:",Q1)
print("Q3:",Q3)
print("IQR:",IQR)

print(f"upper_Bound/ upper_spend(Q3+1.5*IQR): {upper_spend}")
print('OUTLIER=', (df['Spend']>upper_spend).sum())
print("max spend=",df['Spend'].max())

print("median spend=",median_spend)

print("="*80)
print('**upper spend(5576) to max spend(500000.0) has only 73 entry **')
print()

Q1: 663.8874999999999
Q3: 2628.7675
IQR: 1964.88
upper_Bound/ upper_spend(Q3+1.5*IQR): 5576.0875
OUTLIER= 73
max spend= 500000.0
median spend= 1447.725
================================================================================
**upper spend(5576) to max spend(500000.0) has only 73 entry **

In [7]:
# Outlier rows দেখো (top 10 biggest Spend)
upper_spend = 5576.0875
outliers = df[df['Spend'] > upper_spend][['Campaign_ID', 'Channel', 'Spend', 'Clicks', 'CPC', 'Cost_Per_Conversion']]
outliers.sort_values('Spend',ascending=False).head(10)

     Campaign_ID     Channel      Spend  Clicks      CPC  Cost_Per_Conversion
789    CMP-00790    Facebook  500000.00    4272   117.04              2109.70
1460   CMP-01461    Facebook  500000.00    1193   419.11              3125.00
1781   CMP-01782       Email  500000.00     193  2590.67                  NaN
1754   CMP-01755       Email  500000.00    1392   359.20              3030.30
1718   CMP-01719       Email  500000.00    1585   315.46              1886.79
1443   CMP-01444  Google Ads    8921.51    4620     1.93                11.29
1925   CMP-01926    Facebook    8269.90    4606     1.80                12.45
1358   CMP-01359      TikTok    8267.84    4148     1.99                  NaN
1449   CMP-01450  Google Ads    8209.43    4260     1.93                19.93
347    CMP-00348  Google Ads    7583.18    4026     1.88                 9.76

In [8]:
print(df.nlargest(10, 'Spend')[['Spend', 'CPC']]) ## my code

          Spend      CPC
789   500000.00   117.04
1460  500000.00   419.11
1718  500000.00   315.46
1754  500000.00   359.20
1781  500000.00  2590.67
1443    8921.51     1.93
1925    8269.90     1.80
1358    8267.84     1.99
1449    8209.43     1.93
347     7583.18     1.88

In [9]:
print(df.sort_values(['Spend', 'CPC','Cost_Per_Conversion'], ascending=False).head(10)[['Spend', 'CPC','Cost_Per_Conversion']])  ## my code

          Spend      CPC  Cost_Per_Conversion
1781  500000.00  2590.67                  NaN
1460  500000.00   419.11              3125.00
1754  500000.00   359.20              3030.30
1718  500000.00   315.46              1886.79
789   500000.00   117.04              2109.70
1443    8921.51     1.93                11.29
1925    8269.90     1.80                12.45
1358    8267.84     1.99                  NaN
1449    8209.43     1.93                19.93
347     7583.18     1.88                 9.76

In [10]:
# --- Spend Outlier Fix ---
df.loc[df['Spend']>upper_spend,'Spend'] = median_spend
df.loc[789,'Spend']

np.float64(1447.725)

In [11]:
# --- CPC Outlier Fix ---

Q1_CPC=df['CPC'].quantile(0.25)
Q3_CPC=df['CPC'].quantile(0.75)
IQR_CPC= Q3_CPC-Q1_CPC
upper_CPC = Q3_CPC+1.5*IQR_CPC
median_CPC=df['CPC'].median()

df.loc[df['CPC']>upper_CPC,'CPC'] = median_CPC
print(median_CPC)
df.loc[1781,'CPC']

1.25

np.float64(1.25)

In [12]:
# --- Cost_Per_Conversion Outlier Fix ---
Q1_cc=df['Cost_Per_Conversion'].quantile(0.25)
Q3_cc=df['Cost_Per_Conversion'].quantile(0.75)
IQR_cc= Q3_cc-Q1_cc
upper_cc = Q3_cc+1.5*IQR_cc
median_cc=df['Cost_Per_Conversion'].median()

df.loc[df['Cost_Per_Conversion']>upper_cc,'Cost_Per_Conversion'] = median_cc 
print(median_cc)
df.loc[789,'Cost_Per_Conversion']

9.99

np.float64(9.99)

In [13]:
# Verify: Outlier ঠিক হয়েছে কিনা দেখো
print("Max Spend:", df['Spend'].max())
print("Max CPC:", df['CPC'].max())
print("Max Cost_Per_Conversion:", df['Cost_Per_Conversion'].max())
print()
print("Spend outliers remaining:", (df['Spend'] > upper_spend).sum())
print("CPC outliers remaining:", (df['CPC'] > upper_CPC).sum())
print("Cost_Per_Conversion outliers remaining:", (df['Cost_Per_Conversion'] > upper_cc).sum())
print()
print("Mean Spend:", round(df['Spend'].mean(), 2))
print("Median Spend:", df['Spend'].median())
print("Std Spend:", round(df['Spend'].std(), 2))

Max Spend: 5575.21
Max CPC: 2.0
Max Cost_Per_Conversion: 25.64

Spend outliers remaining: 0
CPC outliers remaining: 0
Cost_Per_Conversion outliers remaining: 0

Mean Spend: 1682.01
Median Spend: 1445.7125
Std Spend: 1286.66

In [14]:
print(df.isnull().sum())

Campaign_ID              0
Campaign_Name            0
Start_Date               0
End_Date                 0
Channel                100
Impressions              0
Clicks                   0
Spend                  294
Conversions            200
Active                   0
CTR                      0
CPC                    294
Conversion_Rate        200
Cost_Per_Conversion    463
dtype: int64

In [15]:
# Missing value এর percentage দেখো
print(round(df.isnull().sum()/len(df)*100,2))

Campaign_ID             0.00
Campaign_Name           0.00
Start_Date              0.00
End_Date                0.00
Channel                 5.00
Impressions             0.00
Clicks                  0.00
Spend                  14.70
Conversions            10.00
Active                  0.00
CTR                     0.00
CPC                    14.70
Conversion_Rate        10.00
Cost_Per_Conversion    23.15
dtype: float64

In [16]:

#Channel হলো categorical (text) → তাই Mode ব্যবহার করবো মানে tiktok/facebook er mean/median hoi na
df['Spend'] = df['Spend'].fillna(df['Spend'].median())
df['Channel'] = df['Channel'].fillna(df['Channel'].mode()[0])    ## categorical (text) → তাই Mode ব্যবহার করবো
df['Conversions'] = df['Conversions'].fillna(df['Conversions'].median())
df['CPC'] = df['CPC'].fillna(df['CPC'].median())
df['Conversion_Rate'] = df['Conversion_Rate'].fillna(df['Conversion_Rate'].median())
df['Cost_Per_Conversion'] = df['Cost_Per_Conversion'].fillna(df['Cost_Per_Conversion'].median())

In [17]:
# Missing value এর  দেখো
print(df.isnull().sum())
print('='*80)
print('Total nulls:', df.isnull().sum().sum())

Campaign_ID            0
Campaign_Name          0
Start_Date             0
End_Date               0
Channel                0
Impressions            0
Clicks                 0
Spend                  0
Conversions            0
Active                 0
CTR                    0
CPC                    0
Conversion_Rate        0
Cost_Per_Conversion    0
dtype: int64
================================================================================
Total nulls: 0

In [18]:
#📍 Step 4: Date Columns কে Datetime-এ Convert করা
print('start_date type:',type(df['Start_Date'][0]))
print('end_date type:',type(df['End_Date'][0]))
print('=='*80)

print('=='*80)

#convert to datetime

df['Start_Date']=pd.to_datetime(df['Start_Date']) 
df['End_Date'] = pd.to_datetime(df['End_Date'])

## verify if it converted to datetime

print('type of start date', type(df['Start_Date'][0]))
print('type of end date', type(df['End_Date'][0]))
print('=='*80)
print(df[['Start_Date','End_Date']].head())
print('=='*80)
print('earliest start:',df['Start_Date'].min())
print('latest start:',df['Start_Date'].max())  
print('earliest end:',df['End_Date'].min())
print('latest end:',df['End_Date'].max())

start_date type: <class 'str'>
end_date type: <class 'str'>
================================================================================================================================================================
================================================================================================================================================================
type of start date <class 'pandas._libs.tslibs.timestamps.Timestamp'>
type of end date <class 'pandas._libs.tslibs.timestamps.Timestamp'>
================================================================================================================================================================
  Start_Date   End_Date
0 2023-11-24 2023-12-13
1 2023-05-06 2023-05-12
2 2023-12-13 2023-12-20
3 2023-10-30 2023-11-03
4 2023-04-22 2023-04-23
================================================================================================================================================================
earliest start: 2023-01-01 00:00:00
latest start: 2024-01-01 00:00:00
earliest end: 2022-12-31 00:00:00
latest end: 2024-01-30 00:00:00

In [19]:
## 📍 Step 5: Invalid Dates Fix করা (Start_Date > End_Date)
print('start>end:', (df['Start_Date']>df['End_Date']).sum())

start>end: 78

In [20]:
## or print('start>end:', df[df['Start_Date'] > df['End_Date']].shape[0]) **same result 78

In [21]:
# Invalid date rows দেখো (প্রথম ১০ টা)
df[df['Start_Date'] > df['End_Date']][['Campaign_ID', 'Start_Date', 'End_Date']].head(10)

    Campaign_ID Start_Date   End_Date
23    CMP-00024 2023-05-06 2023-05-01
54    CMP-00055 2023-09-01 2023-08-27
71    CMP-00072 2023-02-01 2023-01-27
124   CMP-00125 2023-04-01 2023-02-02
156   CMP-00157 2023-12-06 2023-12-01
195   CMP-00196 2023-08-04 2023-04-21
200   CMP-00201 2023-01-11 2023-01-06
218   CMP-00219 2023-10-03 2023-09-28
221   CMP-00222 2023-08-26 2023-08-21
241   CMP-00242 2023-10-01 2023-01-11

In [22]:
#সমস্যাটা কী? 78টা row তে Start_Date End_Date-এর পরে আছে। অর্থাৎ ক্যাম্পেইন শেষ হওয়ার পরে শুরু হয়েছে বলে দেখাচ্ছে — যেটা বাস্তবে অসম্ভব!

#কেন ঠিক করতে হবে?

#Campaign duration (কতদিন চলেছে) বের করলে negative আসবে
#Date-based analysis (মাসে কয়টা campaign চলেছে) ভুল হবে
#এটা সম্ভবত data entry mistake — Start ও End উল্টো করে লেখা হয়েছে
#3. 💡 Tip
#💡 Swap Trick: যখন দুইটা কলামের মান উল্টো হয়ে যায়, তখন সবচেয়ে সহজ উপায় হলো swap (বদলাবদলি) করা!

#Pandas-এ এটা একটা line-এই করা যায়:

mask=df['Start_Date'] > df['End_Date']
df.loc[mask,['Start_Date', 'End_Date']]=df.loc[mask,['End_Date', 'Start_Date']].values
print('invalid date swapped')

print('start>end:',mask.sum())
print('='*80)
print('earliest start:',df['Start_Date'].min())
print('latest start:',df['Start_Date'].max())  
print('earliest end:',df['End_Date'].min())
print('latest end:',df['End_Date'].max())

invalid date swapped
start>end: 78
================================================================================
earliest start: 2022-12-31 00:00:00
latest start: 2024-01-01 00:00:00
earliest end: 2023-01-05 00:00:00
latest end: 2024-01-30 00:00:00

In [23]:


# Row 0 এর manually calculated vs stored values compare করো
print("CTR should be: Clicks/Impressions*100 =", round(df['Clicks'][0] / df['Impressions'][0] * 100, 2))
print("CTR currently is:", df['CTR'][0])
print()
print("CPC should be: Spend/Clicks =", round(df['Spend'][0] / df['Clicks'][0], 2))
print("CPC currently is:", df['CPC'][0])
print()
print("Conv Rate should be: Conversions/Clicks*100 =", round(df['Conversions'][0] / df['Clicks'][0] * 100, 2))
print("Conv Rate currently is:", df['Conversion_Rate'][0])
print()
print("Cost/Conv should be: Spend/Conversions =", round(df['Spend'][0] / df['Conversions'][0], 2))
print("Cost/Conv currently is:", df['Cost_Per_Conversion'][0])

CTR should be: Clicks/Impressions*100 = 1.17
CTR currently is: 1.17

CPC should be: Spend/Clicks = 7.34
CPC currently is: 1.25

Conv Rate should be: Conversions/Clicks*100 = 10.15
Conv Rate currently is: 10.15

Cost/Conv should be: Spend/Conversions = 72.29
Cost/Conv currently is: 9.99

In [24]:
#দেখো — CPC হওয়া উচিত 7.34 কিন্তু আছে 1.25 (ভুল!)। Cost/Conv হওয়া উচিত 72.29 কিন্তু আছে 9.99 (ভুল!)। কারণ Row 0 এর Spend আগে NaN ছিল, আমরা median দিয়ে পূরণ করেছি — কিন্তু CPC ও Cost_Per_Conversion পুরোনোই আছে!
#Explanation
#সমস্যাটা কী? CTR, CPC, Conversion_Rate, Cost_Per_Conversion — এগুলো derived columns (অন্য কলাম থেকে বের করা)। যেহেতু আমরা Spend ও Conversions এর মান পরিবর্তন করেছি, তাই এই derived columns এখন outdated (পুরোনো)!

In [25]:
# derived column like cpc and cost/conv recalculate করে save করতে হবে। 
# ***** Save করতে হয় df[] দিয়ে**

#CTR = (Clicks / Impressions) × 100 → recalculate করো
#CPC = Spend / Clicks → recalculate করো
#Conversion_Rate = (Conversions / Clicks) × 100 → recalculate করো
#Cost_Per_Conversion = Spend / Conversions → recalculate করো
#inf values (যদি থাকে) → 0 দিয়ে replace করো

In [26]:

#CTR = (Clicks / Impressions) × 100 → recalculate করো
#CPC = Spend / Clicks → recalculate করো
#Conversion_Rate = (Conversions / Clicks) × 100 → recalculate করো
#Cost_Per_Conversion = Spend / Conversions → recalculate করো
#inf values (যদি থাকে) → 0 দিয়ে replace করো


# CTR recalculate: (Clicks / Impressions) * 100
df['CTR'] = round(df['Clicks'] / df['Impressions'] * 100, 2)

# CPC recalculate: Spend / Clicks
df['CPC'] = round(df['Spend'] / df['Clicks'], 2)

# Conversion_Rate recalculate: (Conversions / Clicks) * 100
df['Conversion_Rate'] = round(df['Conversions'] / df['Clicks'] * 100, 2)

# Cost_Per_Conversion recalculate: Spend / Conversions
df['Cost_Per_Conversion'] = round(df['Spend'] / df['Conversions'], 2)

# inf values থাকলে 0 দিয়ে replace করো (Conversions=0 হলে inf হয়)
df['Cost_Per_Conversion'] = df['Cost_Per_Conversion'].replace([np.inf, -np.inf], 0)

print("Derived columns recalculated!")

Derived columns recalculated!

In [27]:
# Verify: Row 0 এর values এখন সঠিক কিনা দেখো
print(df[['Campaign_ID', 'Impressions', 'Clicks', 'Spend', 'Conversions',
          'CTR', 'CPC', 'Conversion_Rate', 'Cost_Per_Conversion']].head())

  Campaign_ID  Impressions  Clicks      Spend  Conversions   CTR   CPC  \
0   CMP-00001        16795     197  1445.7125         20.0  1.17  7.34
1   CMP-00002         1860      30    24.3300          1.0  1.61  0.81
2   CMP-00003        77820     843  1323.3900         51.0  1.08  1.57
3   CMP-00004        55886    2019  2180.3800        135.0  3.61  1.08
4   CMP-00005         7265     169   252.4400         30.0  2.33  1.49

   Conversion_Rate  Cost_Per_Conversion
0            10.15                72.29
1             3.33                24.33
2             6.05                25.95
3             6.69                16.15
4            17.75                 8.41

In [28]:
# Verify: কোনো inf value নেই
print(f"inf in cost per conversion:", np.isinf(df['Cost_Per_Conversion']).sum())

# Summary stats দেখো

print(df[['CTR', 'CPC', 'Conversion_Rate', 'Cost_Per_Conversion']].describe())

inf in cost per conversion: 0
               CTR          CPC  Conversion_Rate  Cost_Per_Conversion
count  2000.000000  2000.000000      2000.000000          2000.000000
mean      3.003480     1.470550        13.996400            13.694185
std       1.142855     2.850067        23.172874            24.127938
min       0.980000     0.300000         0.000000             0.000000
25%       2.010000     0.800000         8.337500             6.430000
50%       3.045000     1.180000        12.185000             9.805000
75%       3.990000     1.600000        16.060000            14.697500
max       5.000000    72.290000       546.150000           481.900000

In [29]:
df.columns

Index(['Campaign_ID', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel',
       'Impressions', 'Clicks', 'Spend', 'Conversions', 'Active', 'CTR', 'CPC',
       'Conversion_Rate', 'Cost_Per_Conversion'],
      dtype='object')

In [30]:
print(type(df['Active'][0]))
print(type(df['Conversions'][0]))

#or
print(df[['Active', 'Conversions']].dtypes)
print()

print('unique value of active column:',df['Active'].unique())

print(df['Active'].value_counts().sum())
print(df['Conversions'].head(10))

<class 'str'>
<class 'numpy.float64'>
Active          object
Conversions    float64
dtype: object

unique value of active column: ['Yes' 'No']
2000
0     20.0
1      1.0
2     51.0
3    135.0
4     30.0
5    142.0
6    178.0
7    127.0
8    104.0
9    142.0
Name: Conversions, dtype: float64

In [31]:
df['Active']=df['Active'].map({'Yes':True,'No':False})
df['Conversions']=df['Conversions'].astype(int)

In [33]:
print(type(df['Active'][0]))
print(type(df['Conversions'][0]))

#or
print(df[['Active', 'Conversions']].dtypes)
print()
print(df['Active'].head())

print('unique value of active column:',df['Active'].unique())

print(df['Active'].value_counts().sum())
print(df['Conversions'].head(10))

<class 'numpy.bool'>
<class 'numpy.int64'>
Active          bool
Conversions    int64
dtype: object

0     True
1    False
2    False
3     True
4     True
Name: Active, dtype: bool
unique value of active column: [ True False]
2000
0     20
1      1
2     51
3    135
4     30
5    142
6    178
7    127
8    104
9    142
Name: Conversions, dtype: int64

In [36]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Campaign_ID          2000 non-null   object
 1   Campaign_Name        2000 non-null   object
 2   Start_Date           2000 non-null   datetime64[ns]
 3   End_Date             2000 non-null   datetime64[ns]
 4   Channel              2000 non-null   object
 5   Impressions          2000 non-null   int64
 6   Clicks               2000 non-null   int64
 7   Spend                2000 non-null   float64
 8   Conversions          2000 non-null   int64
 9   Active               2000 non-null   bool
 10  CTR                  2000 non-null   float64
 11  CPC                  2000 non-null   float64
 12  Conversion_Rate      2000 non-null   float64
 13  Cost_Per_Conversion  2000 non-null   float64
dtypes: bool(1), datetime64[ns](2), float64(5), int64(3), object(3)
memory usage: 205.2+ KB
None

In [ ]:
# the end

In [ ]:
# ***************************at a glance:************************
#(import pandas as pd
import numpy as np

# === LOAD DATA ===
df = pd.read_csv(r"C:\Users\anikk\Downloads\marketing_campaign_data_cleaned.csv")

# === STEP 1: Fix Negative Values ===
df['Spend'] = df['Spend'].abs()
df['CPC'] = df['CPC'].abs()
df['Cost_Per_Conversion'] = df['Cost_Per_Conversion'].abs()

# === STEP 2: Fix Extreme Outliers (IQR Method → Median Replace) ===
for col in ['Spend', 'CPC', 'Cost_Per_Conversion']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    upper = Q3 + 1.5 * IQR
    median = df[col].median()
    df.loc[df[col] > upper, col] = median

# === STEP 3: Fill Missing Values ===
df['Channel'] = df['Channel'].fillna(df['Channel'].mode()[0])
df['Spend'] = df['Spend'].fillna(df['Spend'].median())
df['Conversions'] = df['Conversions'].fillna(df['Conversions'].median())
df['CPC'] = df['CPC'].fillna(df['CPC'].median())
df['Conversion_Rate'] = df['Conversion_Rate'].fillna(df['Conversion_Rate'].median())
df['Cost_Per_Conversion'] = df['Cost_Per_Conversion'].fillna(df['Cost_Per_Conversion'].median())

# === STEP 4: Convert Date Columns ===
df['Start_Date'] = pd.to_datetime(df['Start_Date'])
df['End_Date'] = pd.to_datetime(df['End_Date'])

# === STEP 5: Fix Invalid Dates (Start > End → Swap) ===
mask = df['Start_Date'] > df['End_Date']
df.loc[mask, ['Start_Date', 'End_Date']] = df.loc[mask, ['End_Date', 'Start_Date']].values

# === STEP 6: Recalculate Derived Columns ===
df['CTR'] = round(df['Clicks'] / df['Impressions'] * 100, 2)
df['CPC'] = round(df['Spend'] / df['Clicks'], 2)
df['Conversion_Rate'] = round(df['Conversions'] / df['Clicks'] * 100, 2)
df['Cost_Per_Conversion'] = round(df['Spend'] / df['Conversions'], 2)
df['Cost_Per_Conversion'] = df['Cost_Per_Conversion'].replace([np.inf, -np.inf], 0)

# === STEP 7: Optimize Data Types ===
df['Active'] = df['Active'].map({'Yes': True, 'No': False})
df['Conversions'] = df['Conversions'].astype(int)

print("✅ All cleaning complete!")
df.info()
)

SyntaxError: unmatched ')' (780184558.py, line 50)